# Настройки сборки TeleMotoMax. Пути к инструментам подставляет build.sh.
MIDP2/midp=###WTK###
MOTOROLA/midp=###WTK###
proguard=###PROGUARD###
antenna_jar=CHANGE ME
target=MOTOROLA
modules=FILES,SMILES_STD,AVATARS
lang=RU
version/jimm=###TMM-VERSION###
version/java=###TMM-VERSION-JAVA###
midlet/name=###TMM-NAME###
